spring:
  application:
    name: notification-server
  datasource:
    url: jdbc:mysql://localhost:3306/notificatoin
    username: root
    password: 98765432
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug